name: "Test"
on:
  push:
    branches:
      - main
  pull_request:
defaults:
  run:
    shell: devenv shell bash -- -e {0}
jobs:
  test:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        name: yuruyomi
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: devenv
    - name: Install devenv.sh
      shell: bash
      run: nix profile install nixpkgs#devenv
    - name: Verify cachix setup
      shell: bash
      run: |
        echo "Checking cachix status..."
        cachix use yuruyomi || echo "Failed to use cachix cache"
        nix --version
        devenv --version
    - name: Check format
      run: check-format
    - name: Check lint
      run: check-lint
    - name: Run backend unit tests
      run: cd backend && cargo test
    - name: Run frontend unittests
      run: test-frontend
    - name: Install needed packages for E2E tests
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y fluxbox x11-xserver-utils gnome-screenshot ffmpeg
    - name: Upload test artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-screenshots
        path: e2e-tests/screenshots/
        if-no-files-found: ignore
